// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
  NEXTJS_ENV: string;
  WORKER_SELF_REFERENCE: Fetcher;
  ASSETS: Fetcher;
}
